### ISSUE TITLE
[no-outline-none]: Using border-color or box-shadow instead border

### ISSUE THREAD

**Issue by YozhikM** [YozhikM/stylelint-a11y#15]
```css
.form-control:focus {
  border-color: #80bdff;
  outline: 0;
}
```
