### ISSUE TITLE
Correct styling is failing when using nested media queries in SCSS

### ISSUE THREAD

**Issue by engelfrost** [YozhikM/stylelint-a11y#38]
I'm using the media-prefers-reduced-motion rule, and am having the following issue with the linter: 

```scss
/* Fails */
.foo {
  transition: all;

  @media (prefers-reduced-motion: reduce) {
    transition: none;
  }
}
```

```css 
/* Works */
.foo {
  transition: all; 
}

@media (prefers-reduced-motion: reduce) {
  .foo {
    transition: none;
  }
}
```

The SCSS in the first code snippet produces the CSS in the second code snippet, yet the first example fails while the second example succeeds.
