### ISSUE TITLE
a11y/media-prefers-reduced-motion: errors out with nested selectors

### ISSUE THREAD

**Issue by mayank99** [YozhikM/stylelint-a11y#64]
The following snippet errors out with `Expected &, * is used with @media (prefers-reduced-motion)`, even though it is perfectly valid.

```scss
@media (prefers-reduced-motion: no-preference) {
  .some-class {
    &, * {
      transition: all 0.2s ease-out;
    }
  }
}
```

EDIT: maybe related to #57
